version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong(!)Password"
      ACCEPT_EULA: "Y"
    restart: always

  stb-api:
    build: .
    container_name: stb-api
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=StbDbContext;User=sa;Password=YourStrong(!)Password;TrustServerCertificate=True
    depends_on:
      - sqlserver
